/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.dialog;

import java.awt.Color;
import util.swing.UIControl;

/**
 *
 * @author Minh Tu
 */
public class BillDetails extends javax.swing.JDialog {

    /**
     * Creates new form BillDetails
     */
    public BillDetails(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        UIControl.setDefaultTableHeader(tableInfo);
        this.getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_BillID = new javax.swing.JLabel();
        scrollPane_Info = new javax.swing.JScrollPane();
        tableInfo = new javax.swing.JTable();
        label_Title = new javax.swing.JLabel();
        labelBillID = new javax.swing.JLabel();
        label_BillDate = new javax.swing.JLabel();
        label_TotalMoney = new javax.swing.JLabel();
        label_GuestMoney = new javax.swing.JLabel();
        label_Change = new javax.swing.JLabel();
        billDate = new javax.swing.JLabel();
        totalMoney = new javax.swing.JLabel();
        guestMoney = new javax.swing.JLabel();
        change = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        label_BillID.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        label_BillID.setText("Bill ID: ");

        tableInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product name", "Amount", "Cost"
            }
        ));
        scrollPane_Info.setViewportView(tableInfo);

        label_Title.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Title.setText("Bill details");

        labelBillID.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        labelBillID.setForeground(new java.awt.Color(255, 51, 51));
        labelBillID.setText("1");

        label_BillDate.setFont(new java.awt.Font("Segoe UI", 2, 15)); // NOI18N
        label_BillDate.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        label_BillDate.setText("Bill date:");

        label_TotalMoney.setFont(new java.awt.Font("Segoe UI", 2, 15)); // NOI18N
        label_TotalMoney.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        label_TotalMoney.setText("Total money:");

        label_GuestMoney.setFont(new java.awt.Font("Segoe UI", 2, 15)); // NOI18N
        label_GuestMoney.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        label_GuestMoney.setText("Guest money:");

        label_Change.setFont(new java.awt.Font("Segoe UI", 2, 15)); // NOI18N
        label_Change.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        label_Change.setText("Change:");

        billDate.setBackground(new java.awt.Color(153, 153, 153));
        billDate.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        billDate.setText("6/9/1969");

        totalMoney.setBackground(new java.awt.Color(153, 153, 153));
        totalMoney.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        totalMoney.setText("499 000 VND");

        guestMoney.setBackground(new java.awt.Color(153, 153, 153));
        guestMoney.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        guestMoney.setText("500 000 VND");

        change.setBackground(new java.awt.Color(153, 153, 153));
        change.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        change.setText("1000 VND");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_Title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollPane_Info, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(label_GuestMoney, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(label_Change, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(label_TotalMoney, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(label_BillDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalMoney)
                                    .addComponent(billDate)
                                    .addComponent(guestMoney)
                                    .addComponent(change)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(label_BillID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelBillID, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(label_Title)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_BillID)
                    .addComponent(labelBillID))
                .addGap(18, 18, 18)
                .addComponent(scrollPane_Info, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_BillDate)
                    .addComponent(billDate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_TotalMoney)
                    .addComponent(totalMoney))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_GuestMoney)
                    .addComponent(guestMoney))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Change)
                    .addComponent(change))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BillDetails dialog = new BillDetails(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel billDate;
    private javax.swing.JLabel change;
    private javax.swing.JLabel guestMoney;
    private javax.swing.JLabel labelBillID;
    private javax.swing.JLabel label_BillDate;
    private javax.swing.JLabel label_BillID;
    private javax.swing.JLabel label_Change;
    private javax.swing.JLabel label_GuestMoney;
    private javax.swing.JLabel label_Title;
    private javax.swing.JLabel label_TotalMoney;
    private javax.swing.JScrollPane scrollPane_Info;
    private javax.swing.JTable tableInfo;
    private javax.swing.JLabel totalMoney;
    // End of variables declaration//GEN-END:variables
}
