/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apitest;

import apitest.AutoSentMail.MailType;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Minh Tu
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    private SimpleDateFormat spd = new SimpleDateFormat("dd/MM/yyyy");

    public Main() {
        initComponents();
        fillTable();
    }
    private DefaultTableModel defaultModel;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableExample = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        button_Template = new javax.swing.JButton();
        button_SendMail = new javax.swing.JButton();
        button_Export = new javax.swing.JButton();
        button_Import = new javax.swing.JButton();
        button_DrawChart = new javax.swing.JButton();
        buttonPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableExample.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tableExample.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Cost", "Amount", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableExample);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0, 30, 0));

        button_Template.setText("Excel Template");
        button_Template.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_TemplateActionPerformed(evt);
            }
        });
        jPanel1.add(button_Template);

        button_SendMail.setText("Send mail");
        button_SendMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_SendMailActionPerformed(evt);
            }
        });
        jPanel1.add(button_SendMail);

        button_Export.setText("Export Excel");
        button_Export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ExportActionPerformed(evt);
            }
        });
        jPanel1.add(button_Export);

        button_Import.setText("Import Excel");
        button_Import.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ImportActionPerformed(evt);
            }
        });
        jPanel1.add(button_Import);

        button_DrawChart.setText("Draw Chart");
        button_DrawChart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_DrawChartActionPerformed(evt);
            }
        });
        jPanel1.add(button_DrawChart);

        buttonPrint.setText("Export Bill");
        buttonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPrintActionPerformed(evt);
            }
        });
        jPanel1.add(buttonPrint);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 904, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(433, 433, 433)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void getDefaultModel() {

    }

    private void fillTable() {
        DefaultTableModel dtm = (DefaultTableModel) tableExample.getModel();

        try {
            Date date1 = spd.parse("24/05/2020");
            Date date2 = spd.parse("25/05/2020");
            Date date3 = spd.parse("26/05/2020");
            Date date4 = spd.parse("27/05/2020");
            Date date5 = spd.parse("28/05/2020");
            Date date6 = spd.parse("29/05/2020");
            Date date7 = spd.parse("30/05/2020");

            Vector row1 = new Vector();
            row1.add(1);
            row1.add("Sugar");
            row1.add(15000);
            row1.add(12);
            row1.add(spd.format(date1));

            dtm.addRow(row1);

            Vector row2 = new Vector();
            row2.add(2);
            row2.add("Pepper");
            row2.add(17000);
            row2.add(8);
            row2.add(spd.format(date2));

            dtm.addRow(row2);

            Vector row3 = new Vector();
            row3.add(3);
            row3.add("Salt");
            row3.add(10000);
            row3.add(4);
            row3.add(spd.format(date3));

            dtm.addRow(row3);

            Vector row4 = new Vector();
            row4.add(3);
            row4.add("Morax");
            row4.add(10000);
            row4.add(7);
            row4.add(spd.format(date4));

            dtm.addRow(row4);

            Vector row5 = new Vector();
            row5.add(3);
            row5.add("Barbatos");
            row5.add(10000);
            row5.add(10);
            row5.add(spd.format(date5));

            dtm.addRow(row5);

            Vector row6 = new Vector();
            row6.add(3);
            row6.add("Rock");
            row6.add(10000);
            row6.add(23);
            row6.add(spd.format(date6));

            dtm.addRow(row6);

            Vector row7 = new Vector();
            row7.add(3);
            row7.add("Ice");
            row7.add(10000);
            row7.add(13);
            row7.add(spd.format(date7));

            dtm.addRow(row7);

        } catch (ParseException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    private void button_ExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ExportActionPerformed

        ExcelExport.exportTableToExcel(tableExample);
    }//GEN-LAST:event_button_ExportActionPerformed

    private void button_DrawChartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_DrawChartActionPerformed
        Chart chart = new Chart("Date", "Amount", tableExample);
        chart.start();
    }//GEN-LAST:event_button_DrawChartActionPerformed

    private void button_SendMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_SendMailActionPerformed
        AutoSentMail mail = new AutoSentMail("minhtu1392000@gmail.com", "thisIsSoStupid", MailType.NEW_PASSWORD);
        mail.start();
        PWRecoveryDialog dialog = new PWRecoveryDialog(null, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_button_SendMailActionPerformed

    private void button_ImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ImportActionPerformed
        ExcelImport.importExcelFileToTable(tableExample);
    }//GEN-LAST:event_button_ImportActionPerformed

    private void button_TemplateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_TemplateActionPerformed
        ExcelImport.createExcelFileTemplate(tableExample);
    }//GEN-LAST:event_button_TemplateActionPerformed

    private void buttonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPrintActionPerformed
        BillPreviewDialog bill = new BillPreviewDialog(this, true);
        bill.setVisible(true);
    }//GEN-LAST:event_buttonPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonPrint;
    private javax.swing.JButton button_DrawChart;
    private javax.swing.JButton button_Export;
    private javax.swing.JButton button_Import;
    private javax.swing.JButton button_SendMail;
    private javax.swing.JButton button_Template;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableExample;
    // End of variables declaration//GEN-END:variables
}
