/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author TRUONG MINH TAN
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialog_confirmExit = new javax.swing.JDialog();
        panel_confirmExit = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        label_confirmExit = new javax.swing.JLabel();
        button_yesExit = new javax.swing.JButton();
        button_noExit = new javax.swing.JButton();
        panel_Login = new javax.swing.JPanel();
        label_signIn = new javax.swing.JLabel();
        label_imgLogo = new javax.swing.JLabel();
        jLabel_dashLine = new javax.swing.JLabel();
        label_email = new javax.swing.JLabel();
        label_password = new javax.swing.JLabel();
        textField_password = new javax.swing.JTextField();
        label_forgotPass = new javax.swing.JLabel();
        label_showPass = new javax.swing.JLabel();
        label_warning = new javax.swing.JLabel();
        button_signIn = new javax.swing.JButton();
        button_exit = new javax.swing.JButton();
        textField_username = new javax.swing.JTextField();
        label_imgUser = new javax.swing.JLabel();
        label_imgPass = new javax.swing.JLabel();

        dialog_confirmExit.setMinimumSize(null);
        dialog_confirmExit.setModal(true);
        dialog_confirmExit.setPreferredSize(new java.awt.Dimension(250, 165));

        panel_confirmExit.setBackground(new java.awt.Color(255, 255, 255));

        jTextField1.setEditable(false);
        jTextField1.setText("Message Report");
        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N

        label_confirmExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_confirmExit.setText("Confirm");
        label_confirmExit.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N

        button_yesExit.setText("YES");
        button_yesExit.setBackground(new java.awt.Color(255, 255, 255));
        button_yesExit.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        button_noExit.setText("NO");
        button_noExit.setBackground(new java.awt.Color(255, 255, 255));
        button_noExit.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        javax.swing.GroupLayout panel_confirmExitLayout = new javax.swing.GroupLayout(panel_confirmExit);
        panel_confirmExit.setLayout(panel_confirmExitLayout);
        panel_confirmExitLayout.setHorizontalGroup(
            panel_confirmExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1)
            .addComponent(label_confirmExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_confirmExitLayout.createSequentialGroup()
                .addComponent(button_yesExit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(button_noExit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_confirmExitLayout.setVerticalGroup(
            panel_confirmExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_confirmExitLayout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label_confirmExit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(panel_confirmExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_yesExit)
                    .addComponent(button_noExit))
                .addContainerGap())
        );

        javax.swing.GroupLayout dialog_confirmExitLayout = new javax.swing.GroupLayout(dialog_confirmExit.getContentPane());
        dialog_confirmExit.getContentPane().setLayout(dialog_confirmExitLayout);
        dialog_confirmExitLayout.setHorizontalGroup(
            dialog_confirmExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_confirmExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        dialog_confirmExitLayout.setVerticalGroup(
            dialog_confirmExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_confirmExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panel_confirmExit.getAccessibleContext().setAccessibleDescription("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        setResizable(false);
        panel_Login.setBackground(new java.awt.Color(255, 255, 255));
        panel_Login.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        label_signIn.setText("Sign In");
        label_signIn.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N

        label_imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N

        jLabel_dashLine.setBackground(new java.awt.Color(0, 204, 204));
        jLabel_dashLine.setOpaque(true);

        label_email.setText("Email:");
        label_email.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        label_password.setText("Password:");
        label_password.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        label_forgotPass.setText("Forgot password");
        label_forgotPass.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        label_forgotPass.setForeground(new java.awt.Color(0, 51, 255));

        label_showPass.setText("Show password");
        label_showPass.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        label_warning.setText("Warning!");
        label_warning.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        button_signIn.setText("SIGN IN");
        button_signIn.setBackground(new java.awt.Color(255, 255, 255));
        button_signIn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        button_exit.setText("EXIT");
        button_exit.setBackground(new java.awt.Color(255, 255, 255));
        button_exit.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        button_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_exitActionPerformed(evt);
            }
        });

        label_imgUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        label_imgUser.setText("jLabel1");

        label_imgPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pass.png"))); // NOI18N

        javax.swing.GroupLayout panel_LoginLayout = new javax.swing.GroupLayout(panel_Login);
        panel_Login.setLayout(panel_LoginLayout);
        panel_LoginLayout.setHorizontalGroup(
            panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_LoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_dashLine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panel_LoginLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(label_signIn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label_imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_LoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_signIn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button_exit)
                .addGap(7, 7, 7))
            .addGroup(panel_LoginLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_LoginLayout.createSequentialGroup()
                        .addComponent(label_warning)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panel_LoginLayout.createSequentialGroup()
                        .addGroup(panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_password)
                            .addComponent(label_email))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_LoginLayout.createSequentialGroup()
                        .addGroup(panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel_LoginLayout.createSequentialGroup()
                                .addGroup(panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textField_username)
                                    .addComponent(textField_password))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_imgPass, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(label_imgUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panel_LoginLayout.createSequentialGroup()
                                .addComponent(label_forgotPass)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                                .addComponent(label_showPass)))
                        .addGap(29, 29, 29))))
        );
        panel_LoginLayout.setVerticalGroup(
            panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_LoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_signIn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_imgLogo))
                .addGap(4, 4, 4)
                .addComponent(jLabel_dashLine, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label_email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_imgUser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textField_username, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_imgPass)
                    .addGroup(panel_LoginLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(textField_password, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_forgotPass)
                    .addComponent(label_showPass))
                .addGap(18, 18, 18)
                .addComponent(label_warning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_signIn)
                    .addComponent(button_exit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_exitActionPerformed
        // TODO add your handling code here:
        dialog_confirmExit.setSize(250,165);
        dialog_confirmExit.setLocationRelativeTo(this);
        dialog_confirmExit.setVisible(true);
      
    }//GEN-LAST:event_button_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_exit;
    private javax.swing.JButton button_noExit;
    private javax.swing.JButton button_signIn;
    private javax.swing.JButton button_yesExit;
    private javax.swing.JDialog dialog_confirmExit;
    private javax.swing.JLabel jLabel_dashLine;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel label_confirmExit;
    private javax.swing.JLabel label_email;
    private javax.swing.JLabel label_forgotPass;
    private javax.swing.JLabel label_imgLogo;
    private javax.swing.JLabel label_imgPass;
    private javax.swing.JLabel label_imgUser;
    private javax.swing.JLabel label_password;
    private javax.swing.JLabel label_showPass;
    private javax.swing.JLabel label_signIn;
    private javax.swing.JLabel label_warning;
    private javax.swing.JPanel panel_Login;
    private javax.swing.JPanel panel_confirmExit;
    private javax.swing.JTextField textField_password;
    private javax.swing.JTextField textField_username;
    // End of variables declaration//GEN-END:variables
}
