/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;



/**
 *
 * @author TRUONG MINH TAN
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialog_confirmExit = new javax.swing.JDialog();
        panel_confirmExit = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        label_confirmExit = new javax.swing.JLabel();
        button_yesExit = new javax.swing.JButton();
        button_noExit = new javax.swing.JButton();
        dialog_recoverPassword = new javax.swing.JDialog();
        label_recoverPass = new javax.swing.JLabel();
        label_recoverEmail = new javax.swing.JLabel();
        recover_empID = new javax.swing.JLabel();
        textField_recoEmail = new javax.swing.JTextField();
        textField_recoEmpID = new javax.swing.JTextField();
        button_recover = new javax.swing.JButton();
        panel_Login = new javax.swing.JPanel();
        label_signIn = new javax.swing.JLabel();
        label_imgLogo = new javax.swing.JLabel();
        jLabel_dashLine = new javax.swing.JLabel();
        label_email = new javax.swing.JLabel();
        label_password = new javax.swing.JLabel();
        textField_username = new javax.swing.JTextField();
        label_imgUser = new javax.swing.JLabel();
        label_imgPass = new javax.swing.JLabel();
        passwordField_Password = new javax.swing.JPasswordField();
        checkbox_ShowPassword = new javax.swing.JCheckBox();
        button_signIn = new javax.swing.JButton();
        button_forgotPassword = new javax.swing.JButton();

        dialog_confirmExit.setMinimumSize(null);
        dialog_confirmExit.setModal(true);

        panel_confirmExit.setBackground(new java.awt.Color(255, 255, 255));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jTextField1.setText("Message Report");

        label_confirmExit.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        label_confirmExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_confirmExit.setText("Confirm");

        button_yesExit.setBackground(new java.awt.Color(255, 255, 255));
        button_yesExit.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        button_yesExit.setText("YES");

        button_noExit.setBackground(new java.awt.Color(255, 255, 255));
        button_noExit.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        button_noExit.setText("NO");

        javax.swing.GroupLayout panel_confirmExitLayout = new javax.swing.GroupLayout(panel_confirmExit);
        panel_confirmExit.setLayout(panel_confirmExitLayout);
        panel_confirmExitLayout.setHorizontalGroup(
            panel_confirmExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1)
            .addComponent(label_confirmExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_confirmExitLayout.createSequentialGroup()
                .addComponent(button_yesExit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(button_noExit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_confirmExitLayout.setVerticalGroup(
            panel_confirmExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_confirmExitLayout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label_confirmExit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(panel_confirmExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_yesExit)
                    .addComponent(button_noExit))
                .addContainerGap())
        );

        javax.swing.GroupLayout dialog_confirmExitLayout = new javax.swing.GroupLayout(dialog_confirmExit.getContentPane());
        dialog_confirmExit.getContentPane().setLayout(dialog_confirmExitLayout);
        dialog_confirmExitLayout.setHorizontalGroup(
            dialog_confirmExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_confirmExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        dialog_confirmExitLayout.setVerticalGroup(
            dialog_confirmExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_confirmExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panel_confirmExit.getAccessibleContext().setAccessibleDescription("");

        dialog_recoverPassword.setResizable(false);

        label_recoverPass.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        label_recoverPass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_recoverPass.setText("RECOVER PASSWORD");

        label_recoverEmail.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        label_recoverEmail.setText("Email");

        recover_empID.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        recover_empID.setText("Employee ID");

        textField_recoEmail.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        textField_recoEmail.setPreferredSize(new java.awt.Dimension(160, 30));

        textField_recoEmpID.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        textField_recoEmpID.setPreferredSize(new java.awt.Dimension(160, 30));

        button_recover.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        button_recover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttonIMG_sendPW.png"))); // NOI18N
        button_recover.setContentAreaFilled(false);
        button_recover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_recoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialog_recoverPasswordLayout = new javax.swing.GroupLayout(dialog_recoverPassword.getContentPane());
        dialog_recoverPassword.getContentPane().setLayout(dialog_recoverPasswordLayout);
        dialog_recoverPasswordLayout.setHorizontalGroup(
            dialog_recoverPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_recoverPasswordLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dialog_recoverPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialog_recoverPasswordLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(label_recoverPass, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialog_recoverPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(button_recover)
                        .addGroup(dialog_recoverPasswordLayout.createSequentialGroup()
                            .addGroup(dialog_recoverPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(recover_empID)
                                .addComponent(label_recoverEmail))
                            .addGroup(dialog_recoverPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(dialog_recoverPasswordLayout.createSequentialGroup()
                                    .addGap(21, 21, 21)
                                    .addComponent(textField_recoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(dialog_recoverPasswordLayout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(textField_recoEmpID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
        );
        dialog_recoverPasswordLayout.setVerticalGroup(
            dialog_recoverPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_recoverPasswordLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(label_recoverPass)
                .addGap(18, 18, 18)
                .addGroup(dialog_recoverPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_recoverEmail)
                    .addComponent(textField_recoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialog_recoverPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textField_recoEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recover_empID))
                .addGap(18, 18, 18)
                .addComponent(button_recover)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign In");

        setResizable(false);
        panel_Login.setBackground(new java.awt.Color(255, 255, 255));
        panel_Login.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        label_signIn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        label_signIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_signIn.setText("Cake Shop Management");

        label_imgLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logo_60px.png"))); // NOI18N
        label_imgLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel_dashLine.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_dashLine.setOpaque(true);

        label_email.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        label_email.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_email.setText("Email:");
        label_email.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        label_password.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        label_password.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_password.setText("Password:");
        label_password.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        textField_username.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        label_imgUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_User.png"))); // NOI18N
        label_imgUser.setText("jLabel1");

        label_imgPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_Password.png"))); // NOI18N

        passwordField_Password.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        checkbox_ShowPassword.setBackground(new java.awt.Color(255, 255, 255));
        checkbox_ShowPassword.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        checkbox_ShowPassword.setText("Show password");
        checkbox_ShowPassword.setFocusPainted(false);

        button_signIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttonIMG_signIn.png"))); // NOI18N
        button_signIn.setContentAreaFilled(false);
        button_signIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_signIn.setFocusPainted(false);
        button_signIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_signInActionPerformed(evt);
            }
        });

        button_forgotPassword.setBackground(new java.awt.Color(51, 102, 255));
        button_forgotPassword.setFont(new java.awt.Font("Segoe UI", 2, 15)); // NOI18N
        button_forgotPassword.setForeground(new java.awt.Color(0, 123, 255));
        button_forgotPassword.setText("Forgot password?");
        button_forgotPassword.setContentAreaFilled(false);
        button_forgotPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_forgotPassword.setFocusPainted(false);
        button_forgotPassword.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        button_forgotPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_forgotPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_LoginLayout = new javax.swing.GroupLayout(panel_Login);
        panel_Login.setLayout(panel_LoginLayout);
        panel_LoginLayout.setHorizontalGroup(
            panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_LoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_dashLine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panel_LoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_signIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(panel_LoginLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_LoginLayout.createSequentialGroup()
                        .addGroup(panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_email)
                            .addComponent(label_password))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_LoginLayout.createSequentialGroup()
                        .addGroup(panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(button_signIn, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                            .addGroup(panel_LoginLayout.createSequentialGroup()
                                .addGroup(panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel_LoginLayout.createSequentialGroup()
                                        .addComponent(button_forgotPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(checkbox_ShowPassword))
                                    .addComponent(passwordField_Password)
                                    .addComponent(textField_username, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_imgPass)
                                    .addComponent(label_imgUser, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(23, 23, 23))))
        );
        panel_LoginLayout.setVerticalGroup(
            panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_LoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_LoginLayout.createSequentialGroup()
                        .addComponent(label_imgLogo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_LoginLayout.createSequentialGroup()
                        .addComponent(label_signIn)
                        .addGap(26, 26, 26)))
                .addComponent(jLabel_dashLine, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_email)
                .addGap(3, 3, 3)
                .addGroup(panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textField_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_imgUser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_imgPass)
                    .addComponent(passwordField_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkbox_ShowPassword)
                    .addComponent(button_forgotPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(button_signIn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button_signInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_signInActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_button_signInActionPerformed

    private void button_recoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_recoverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_recoverActionPerformed

    private void button_forgotPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_forgotPasswordActionPerformed
        dialog_recoverPassword.setSize(401,280);
        dialog_recoverPassword.setLocationRelativeTo(this);
        dialog_recoverPassword.setVisible(true);
    }//GEN-LAST:event_button_forgotPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_forgotPassword;
    private javax.swing.JButton button_noExit;
    private javax.swing.JButton button_recover;
    private javax.swing.JButton button_signIn;
    private javax.swing.JButton button_yesExit;
    private javax.swing.JCheckBox checkbox_ShowPassword;
    private javax.swing.JDialog dialog_confirmExit;
    private javax.swing.JDialog dialog_recoverPassword;
    private javax.swing.JLabel jLabel_dashLine;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel label_confirmExit;
    private javax.swing.JLabel label_email;
    private javax.swing.JLabel label_imgLogo;
    private javax.swing.JLabel label_imgPass;
    private javax.swing.JLabel label_imgUser;
    private javax.swing.JLabel label_password;
    private javax.swing.JLabel label_recoverEmail;
    private javax.swing.JLabel label_recoverPass;
    private javax.swing.JLabel label_signIn;
    private javax.swing.JPanel panel_Login;
    private javax.swing.JPanel panel_confirmExit;
    private javax.swing.JPasswordField passwordField_Password;
    private javax.swing.JLabel recover_empID;
    private javax.swing.JTextField textField_recoEmail;
    private javax.swing.JTextField textField_recoEmpID;
    private javax.swing.JTextField textField_username;
    // End of variables declaration//GEN-END:variables
}
