/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author TRUONG MINH TAN
 */
public class recoverPass extends javax.swing.JFrame {

    /**
     * Creates new form recoverPasso
     */
    public recoverPass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_recoverPass = new javax.swing.JPanel();
        label_recoverPass = new javax.swing.JLabel();
        label_recoverEmail = new javax.swing.JLabel();
        recover_empID = new javax.swing.JLabel();
        textField_recoEmail = new javax.swing.JTextField();
        textField_recoEmpID = new javax.swing.JTextField();
        button_recover = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_recoverPass.setBackground(new java.awt.Color(255, 255, 255));

        label_recoverPass.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        label_recoverPass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_recoverPass.setText("Recover Password");

        label_recoverEmail.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        label_recoverEmail.setText("Email");

        recover_empID.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        recover_empID.setText("Employee ID");

        textField_recoEmail.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        textField_recoEmail.setPreferredSize(new java.awt.Dimension(160, 30));

        textField_recoEmpID.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        textField_recoEmpID.setPreferredSize(new java.awt.Dimension(160, 30));

        button_recover.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        button_recover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button_recover-password.png"))); // NOI18N
        button_recover.setContentAreaFilled(false);

        javax.swing.GroupLayout panel_recoverPassLayout = new javax.swing.GroupLayout(panel_recoverPass);
        panel_recoverPass.setLayout(panel_recoverPassLayout);
        panel_recoverPassLayout.setHorizontalGroup(
            panel_recoverPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_recoverPass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_recoverPassLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_recoverPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(recover_empID)
                    .addComponent(label_recoverEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_recoverPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textField_recoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textField_recoEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
            .addComponent(button_recover, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        panel_recoverPassLayout.setVerticalGroup(
            panel_recoverPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_recoverPassLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_recoverPass)
                .addGap(18, 18, 18)
                .addGroup(panel_recoverPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_recoverEmail)
                    .addComponent(textField_recoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(panel_recoverPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recover_empID)
                    .addComponent(textField_recoEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(button_recover)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_recoverPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_recoverPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(recoverPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(recoverPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(recoverPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(recoverPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new recoverPass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_recover;
    private javax.swing.JLabel label_recoverEmail;
    private javax.swing.JLabel label_recoverPass;
    private javax.swing.JPanel panel_recoverPass;
    private javax.swing.JLabel recover_empID;
    private javax.swing.JTextField textField_recoEmail;
    private javax.swing.JTextField textField_recoEmpID;
    // End of variables declaration//GEN-END:variables
}
