/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Functions;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Minh Tu
 */
public class Function_Home extends javax.swing.JPanel {
//new ImageIcon(getClass().getResource("/img/edited.png")).getImage();
    /**
     * Creates new form Function_Home
     *///
    private Image img;
    public Function_Home(){
        initComponents();
        this.img = null;
    }
    
 
  public Function_Home(Image img) {
    initComponents();
    this.img = img;
  }
  @Override
  public void paintComponent(Graphics g) {
    super.paintComponent(g);
    g.drawImage(img, 0, 0, null);
  }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_Today = new javax.swing.JLabel();
        panel_Revenue = new javax.swing.JPanel();
        label_Title_Rev = new javax.swing.JLabel();
        label_RevAmount = new javax.swing.JLabel();
        background_Rev = new javax.swing.JLabel();
        panel_Profit = new javax.swing.JPanel();
        label_Title_Profit = new javax.swing.JLabel();
        label_ProfitAmount = new javax.swing.JLabel();
        background_Profit = new javax.swing.JLabel();
        panel_Bills = new javax.swing.JPanel();
        label_Title_Bills = new javax.swing.JLabel();
        label_BillsAmount = new javax.swing.JLabel();
        background_Bills = new javax.swing.JLabel();
        label_Seperator = new javax.swing.JLabel();
        label_Numbers = new javax.swing.JLabel();
        panel_Employee = new javax.swing.JPanel();
        label_Title_Employee = new javax.swing.JLabel();
        label_EmployeeAmount = new javax.swing.JLabel();
        background_Employee = new javax.swing.JLabel();
        panel_CakeType = new javax.swing.JPanel();
        label_Title_CakeType = new javax.swing.JLabel();
        label_CakeTypeAmount = new javax.swing.JLabel();
        background_CakeType = new javax.swing.JLabel();

        label_Today.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Today.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button_today.png"))); // NOI18N

        panel_Revenue.setOpaque(false);
        panel_Revenue.setLayout(null);

        label_Title_Rev.setFont(new java.awt.Font("Segoe Print", 2, 28)); // NOI18N
        label_Title_Rev.setForeground(new java.awt.Color(0, 0, 0));
        label_Title_Rev.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Title_Rev.setText("Revenue");
        panel_Revenue.add(label_Title_Rev);
        label_Title_Rev.setBounds(50, 40, 230, 70);

        label_RevAmount.setFont(new java.awt.Font("Segoe Print", 3, 32)); // NOI18N
        label_RevAmount.setForeground(new java.awt.Color(253, 94, 83));
        label_RevAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_RevAmount.setText("2000K");
        panel_Revenue.add(label_RevAmount);
        label_RevAmount.setBounds(30, 80, 260, 90);

        background_Rev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/blue_25.png"))); // NOI18N
        background_Rev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                background_RevMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                background_RevMouseExited(evt);
            }
        });
        panel_Revenue.add(background_Rev);
        background_Rev.setBounds(30, 20, 270, 190);

        panel_Profit.setOpaque(false);
        panel_Profit.setLayout(null);

        label_Title_Profit.setFont(new java.awt.Font("Segoe Print", 2, 28)); // NOI18N
        label_Title_Profit.setForeground(new java.awt.Color(0, 0, 0));
        label_Title_Profit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Title_Profit.setText("Profit");
        panel_Profit.add(label_Title_Profit);
        label_Title_Profit.setBounds(50, 40, 230, 70);

        label_ProfitAmount.setFont(new java.awt.Font("Segoe Print", 3, 32)); // NOI18N
        label_ProfitAmount.setForeground(new java.awt.Color(253, 94, 83));
        label_ProfitAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_ProfitAmount.setText("500K");
        panel_Profit.add(label_ProfitAmount);
        label_ProfitAmount.setBounds(30, 80, 260, 90);

        background_Profit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/blue_25.png"))); // NOI18N
        background_Profit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                background_ProfitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                background_ProfitMouseExited(evt);
            }
        });
        panel_Profit.add(background_Profit);
        background_Profit.setBounds(30, 20, 270, 190);

        panel_Bills.setOpaque(false);
        panel_Bills.setLayout(null);

        label_Title_Bills.setFont(new java.awt.Font("Segoe Print", 2, 28)); // NOI18N
        label_Title_Bills.setForeground(new java.awt.Color(0, 0, 0));
        label_Title_Bills.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Title_Bills.setText("Bills");
        panel_Bills.add(label_Title_Bills);
        label_Title_Bills.setBounds(50, 40, 230, 70);

        label_BillsAmount.setFont(new java.awt.Font("Segoe Print", 3, 32)); // NOI18N
        label_BillsAmount.setForeground(new java.awt.Color(253, 94, 83));
        label_BillsAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_BillsAmount.setText("23");
        panel_Bills.add(label_BillsAmount);
        label_BillsAmount.setBounds(30, 80, 260, 90);

        background_Bills.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/blue_25.png"))); // NOI18N
        background_Bills.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                background_BillsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                background_BillsMouseExited(evt);
            }
        });
        panel_Bills.add(background_Bills);
        background_Bills.setBounds(30, 20, 270, 190);

        label_Seperator.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Seperator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seperator.png"))); // NOI18N

        label_Numbers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Numbers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button_numbers.png"))); // NOI18N

        panel_Employee.setOpaque(false);
        panel_Employee.setLayout(null);

        label_Title_Employee.setFont(new java.awt.Font("Segoe Print", 2, 28)); // NOI18N
        label_Title_Employee.setForeground(new java.awt.Color(0, 0, 0));
        label_Title_Employee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Title_Employee.setText("Employee");
        panel_Employee.add(label_Title_Employee);
        label_Title_Employee.setBounds(50, 40, 230, 70);

        label_EmployeeAmount.setFont(new java.awt.Font("Segoe Print", 3, 32)); // NOI18N
        label_EmployeeAmount.setForeground(new java.awt.Color(253, 94, 83));
        label_EmployeeAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_EmployeeAmount.setText("9");
        panel_Employee.add(label_EmployeeAmount);
        label_EmployeeAmount.setBounds(30, 80, 260, 90);

        background_Employee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/blue_25.png"))); // NOI18N
        background_Employee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                background_EmployeeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                background_EmployeeMouseExited(evt);
            }
        });
        panel_Employee.add(background_Employee);
        background_Employee.setBounds(30, 10, 270, 190);

        panel_CakeType.setOpaque(false);
        panel_CakeType.setLayout(null);

        label_Title_CakeType.setFont(new java.awt.Font("Segoe Print", 2, 28)); // NOI18N
        label_Title_CakeType.setForeground(new java.awt.Color(0, 0, 0));
        label_Title_CakeType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Title_CakeType.setText("Cake type");
        panel_CakeType.add(label_Title_CakeType);
        label_Title_CakeType.setBounds(50, 40, 230, 70);

        label_CakeTypeAmount.setFont(new java.awt.Font("Segoe Print", 3, 32)); // NOI18N
        label_CakeTypeAmount.setForeground(new java.awt.Color(253, 94, 83));
        label_CakeTypeAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_CakeTypeAmount.setText("13");
        panel_CakeType.add(label_CakeTypeAmount);
        label_CakeTypeAmount.setBounds(30, 80, 260, 90);

        background_CakeType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/blue_25.png"))); // NOI18N
        background_CakeType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                background_CakeTypeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                background_CakeTypeMouseExited(evt);
            }
        });
        panel_CakeType.add(background_CakeType);
        background_CakeType.setBounds(30, 20, 270, 190);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label_Today, javax.swing.GroupLayout.DEFAULT_SIZE, 1211, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_Seperator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panel_Revenue, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(94, 94, 94)
                                .addComponent(panel_Bills, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panel_Profit, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(label_Numbers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(panel_CakeType, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel_Employee, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(label_Today, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_Revenue, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_Profit, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(panel_Bills, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_Seperator, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(label_Numbers, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_CakeType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_Employee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void background_RevMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_background_RevMouseEntered
        background_Rev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/red_25.png")));
        label_RevAmount.setForeground(new Color(186, 232, 232));
        label_Title_Rev.setForeground(Color.WHITE);
    }//GEN-LAST:event_background_RevMouseEntered

    private void background_RevMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_background_RevMouseExited
        background_Rev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/blue_25.png")));
        label_RevAmount.setForeground(new Color(253, 94, 83));
        label_Title_Rev.setForeground(Color.BLACK);
    }//GEN-LAST:event_background_RevMouseExited

    private void background_ProfitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_background_ProfitMouseEntered
        background_Profit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/red_25.png")));
        label_ProfitAmount.setForeground(new Color(186, 232, 232));
        label_Title_Profit.setForeground(Color.WHITE);
    }//GEN-LAST:event_background_ProfitMouseEntered

    private void background_ProfitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_background_ProfitMouseExited
        background_Profit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/blue_25.png")));
        label_ProfitAmount.setForeground(new Color(253, 94, 83));
        label_Title_Profit.setForeground(Color.BLACK);
    }//GEN-LAST:event_background_ProfitMouseExited

    private void background_BillsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_background_BillsMouseEntered
        background_Bills.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/red_25.png")));
        label_BillsAmount.setForeground(new Color(186, 232, 232));
        label_Title_Bills.setForeground(Color.WHITE);
    }//GEN-LAST:event_background_BillsMouseEntered

    private void background_BillsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_background_BillsMouseExited
        background_Bills.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/blue_25.png")));
        label_BillsAmount.setForeground(new Color(253, 94, 83));
        label_Title_Bills.setForeground(Color.BLACK);
    }//GEN-LAST:event_background_BillsMouseExited

    private void background_EmployeeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_background_EmployeeMouseEntered
        background_Employee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/red_25.png")));
        label_EmployeeAmount.setForeground(new Color(186, 232, 232));
        label_Title_Employee.setForeground(Color.WHITE);
    }//GEN-LAST:event_background_EmployeeMouseEntered

    private void background_EmployeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_background_EmployeeMouseExited
        background_Employee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/blue_25.png")));
        label_EmployeeAmount.setForeground(new Color(253, 94, 83));
        label_Title_Employee.setForeground(Color.BLACK);
    }//GEN-LAST:event_background_EmployeeMouseExited

    private void background_CakeTypeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_background_CakeTypeMouseEntered
        background_CakeType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/red_25.png")));
        label_CakeTypeAmount.setForeground(new Color(186, 232, 232));
        label_Title_CakeType.setForeground(Color.WHITE);
    }//GEN-LAST:event_background_CakeTypeMouseEntered

    private void background_CakeTypeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_background_CakeTypeMouseExited
        background_CakeType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/blue_25.png")));
        label_CakeTypeAmount.setForeground(new Color(253, 94, 83));
        label_Title_CakeType.setForeground(Color.BLACK);
    }//GEN-LAST:event_background_CakeTypeMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background_Bills;
    private javax.swing.JLabel background_CakeType;
    private javax.swing.JLabel background_Employee;
    private javax.swing.JLabel background_Profit;
    private javax.swing.JLabel background_Rev;
    private javax.swing.JLabel label_BillsAmount;
    private javax.swing.JLabel label_CakeTypeAmount;
    private javax.swing.JLabel label_EmployeeAmount;
    private javax.swing.JLabel label_Numbers;
    private javax.swing.JLabel label_ProfitAmount;
    private javax.swing.JLabel label_RevAmount;
    private javax.swing.JLabel label_Seperator;
    private javax.swing.JLabel label_Title_Bills;
    private javax.swing.JLabel label_Title_CakeType;
    private javax.swing.JLabel label_Title_Employee;
    private javax.swing.JLabel label_Title_Profit;
    private javax.swing.JLabel label_Title_Rev;
    private javax.swing.JLabel label_Today;
    private javax.swing.JPanel panel_Bills;
    private javax.swing.JPanel panel_CakeType;
    private javax.swing.JPanel panel_Employee;
    private javax.swing.JPanel panel_Profit;
    private javax.swing.JPanel panel_Revenue;
    // End of variables declaration//GEN-END:variables
}
