package view.main;

import view.login.LoginUpdateObserver;
import javax.swing.ImageIcon;
import model.user.UserModelInterface;

public abstract class MainFrameAbstract extends javax.swing.JFrame implements LoginUpdateObserver {

    private UserModelInterface model;

    /**
     * Creates new form MainFrame
     */
    public MainFrameAbstract(UserModelInterface model) {
        initComponents();

        this.model = model;
        this.model.registerObserver(this);

        panelSideMenu.showCardMenu("Home");
    }

    @Override
    public void updateState() {
        if (this.model != null) {
            this.setVisible(true);
        }
    }
    
    public abstract void showMainFrame();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        panelTitle = new view.TitleMainFrame();
        panelManage = new javax.swing.JPanel();
        panelEmployeeManage = new view.function.EmployeeManagePanel();
        panelHome = new view.function.HomePanel(new ImageIcon(getClass().getResource("/img/homeBackground.png")).getImage());
        panelStatistics = new view.function.StatisticsPanel();
        panelProduct = new view.function.product.ProductManagePanel();
        panelBill = new view.function.bill.BillManagePanel();
        panelSideMenu = new view.SideMenuPanel(panelTitle.getLabel_title(), panelManage);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelManage.setLayout(new java.awt.CardLayout());

        panelEmployeeManage.setName("Employee"); // NOI18N
        panelManage.add(panelEmployeeManage, "Employee");

        panelHome.setName("Home"); // NOI18N
        panelManage.add(panelHome, "Home");

        panelStatistics.setName("Statistics"); // NOI18N
        panelManage.add(panelStatistics, "Statistics");

        panelProduct.setName("Product"); // NOI18N
        panelManage.add(panelProduct, "Product");

        panelBill.setName("Selling"); // NOI18N
        panelManage.add(panelBill, "Selling");

        jLayeredPane1.setLayer(panelTitle, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(panelManage, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(panelSideMenu, javax.swing.JLayeredPane.DRAG_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSideMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(panelManage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(panelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 1246, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(panelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelManage, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(panelSideMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private view.function.bill.BillManagePanel panelBill;
    private view.function.EmployeeManagePanel panelEmployeeManage;
    private view.function.HomePanel panelHome;
    private javax.swing.JPanel panelManage;
    private view.function.product.ProductManagePanel panelProduct;
    private view.SideMenuPanel panelSideMenu;
    private view.function.StatisticsPanel panelStatistics;
    private view.TitleMainFrame panelTitle;
    // End of variables declaration//GEN-END:variables

}
