/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.function.product;

import util.swing.UIControl;
import view.dialog.ImportHistoryDialog;
import view.dialog.IngredientImportDialog;
import view.dialog.NewIngredientTypeCreateDialog;

/**
 *
 * @author DELL
 */
public class IngredientPanel extends javax.swing.JPanel {

    /**
     * Creates new form IngredientManagePanel
     */
    NewIngredientTypeCreateDialog newIngredientTypeCreateDialog = new NewIngredientTypeCreateDialog(null, true);
    IngredientImportDialog ingredientImportDialog = new IngredientImportDialog(null, true);
    ImportHistoryDialog history = new ImportHistoryDialog(null, true);

    public IngredientPanel() {
        initComponents();
        setEditableForAll(false);
        UIControl.setDefaultTableHeader(tableIngredient);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelIngredientInfo = new javax.swing.JPanel();
        label_ingreID = new javax.swing.JLabel();
        textfID = new javax.swing.JTextField();
        label_ingreName = new javax.swing.JLabel();
        label_ingreCost = new javax.swing.JLabel();
        label_ingreType = new javax.swing.JLabel();
        combType = new javax.swing.JComboBox<>();
        btnAddType = new javax.swing.JButton();
        label_IngredientProvider = new javax.swing.JLabel();
        textfName = new javax.swing.JTextField();
        textfCost = new javax.swing.JTextField();
        textfProviderName = new javax.swing.JTextField();
        label_Search = new javax.swing.JLabel();
        textfSearch = new javax.swing.JTextField();
        scrpaneIngredient = new javax.swing.JScrollPane();
        tableIngredient = new javax.swing.JTable();
        panelBtn = new javax.swing.JPanel();
        btnExport = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnModify = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnImport = new javax.swing.JButton();
        button_ShowImportHistory = new javax.swing.JButton();
        button_ClearSearch = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        panelIngredientInfo.setBackground(new java.awt.Color(255, 255, 255));
        panelIngredientInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingredient Information", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 14), new java.awt.Color(153, 153, 153))); // NOI18N

        label_ingreID.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        label_ingreID.setText(" ID");

        textfID.setEditable(false);
        textfID.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        textfID.setPreferredSize(new java.awt.Dimension(160, 30));

        label_ingreName.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        label_ingreName.setText(" Name");

        label_ingreCost.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        label_ingreCost.setText("Cost");

        label_ingreType.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        label_ingreType.setText("Ingredient Type");

        combType.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        combType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combType.setPreferredSize(new java.awt.Dimension(160, 30));

        btnAddType.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnAddType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button_new-type.png"))); // NOI18N
        btnAddType.setContentAreaFilled(false);
        btnAddType.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddType.setFocusPainted(false);
        btnAddType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTypeActionPerformed(evt);
            }
        });

        label_IngredientProvider.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        label_IngredientProvider.setText("Provider");

        textfName.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        textfCost.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        textfProviderName.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        textfProviderName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfProviderNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelIngredientInfoLayout = new javax.swing.GroupLayout(panelIngredientInfo);
        panelIngredientInfo.setLayout(panelIngredientInfoLayout);
        panelIngredientInfoLayout.setHorizontalGroup(
            panelIngredientInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIngredientInfoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panelIngredientInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_ingreName)
                    .addComponent(label_ingreID))
                .addGap(18, 18, 18)
                .addGroup(panelIngredientInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIngredientInfoLayout.createSequentialGroup()
                        .addComponent(textfID, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label_ingreType)
                        .addGap(18, 18, 18)
                        .addComponent(combType, 0, 165, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddType))
                    .addGroup(panelIngredientInfoLayout.createSequentialGroup()
                        .addComponent(textfName, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label_ingreCost)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textfCost)))
                .addGap(17, 17, 17))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIngredientInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label_IngredientProvider)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textfProviderName, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(176, 176, 176))
        );
        panelIngredientInfoLayout.setVerticalGroup(
            panelIngredientInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIngredientInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIngredientInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_ingreID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddType, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_ingreType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelIngredientInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_ingreName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_ingreCost, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelIngredientInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_IngredientProvider, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfProviderName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        label_Search.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        label_Search.setText("Type name to search");

        textfSearch.setPreferredSize(new java.awt.Dimension(190, 30));
        textfSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfSearchActionPerformed(evt);
            }
        });

        tableIngredient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "ID", "Name", "Cost", "Type", "Total amount", "Unit", "Provider"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrpaneIngredient.setViewportView(tableIngredient);

        panelBtn.setBackground(new java.awt.Color(255, 255, 255));
        panelBtn.setLayout(new java.awt.GridLayout(1, 0, 40, 0));

        btnExport.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnExport.setText("Export");
        btnExport.setFocusPainted(false);
        btnExport.setPreferredSize(new java.awt.Dimension(115, 40));
        panelBtn.add(btnExport);

        btnAdd.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.setFocusPainted(false);
        btnAdd.setPreferredSize(new java.awt.Dimension(115, 40));
        panelBtn.add(btnAdd);

        btnModify.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnModify.setText("Modify");
        btnModify.setFocusPainted(false);
        btnModify.setPreferredSize(new java.awt.Dimension(115, 40));
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });
        panelBtn.add(btnModify);

        btnRemove.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnRemove.setText("Remove");
        btnRemove.setFocusPainted(false);
        btnRemove.setPreferredSize(new java.awt.Dimension(115, 40));
        panelBtn.add(btnRemove);

        btnImport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button_import-selected-ingredient.png"))); // NOI18N
        btnImport.setContentAreaFilled(false);
        btnImport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnImport.setFocusPainted(false);
        btnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportActionPerformed(evt);
            }
        });

        button_ShowImportHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button_show-import-history.png"))); // NOI18N
        button_ShowImportHistory.setContentAreaFilled(false);
        button_ShowImportHistory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_ShowImportHistory.setFocusPainted(false);
        button_ShowImportHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ShowImportHistoryActionPerformed(evt);
            }
        });

        button_ClearSearch.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        button_ClearSearch.setText("Clear");
        button_ClearSearch.setFocusPainted(false);
        button_ClearSearch.setPreferredSize(new java.awt.Dimension(89, 29));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrpaneIngredient)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_Search)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(button_ClearSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(panelIngredientInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(panelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(250, Short.MAX_VALUE)
                .addComponent(btnImport)
                .addGap(54, 54, 54)
                .addComponent(button_ShowImportHistory)
                .addGap(250, 250, 250))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(panelIngredientInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label_Search)
                        .addComponent(textfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(button_ClearSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, Short.MAX_VALUE))
                    .addComponent(panelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scrpaneIngredient, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_ShowImportHistory, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnImport, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void setEditableForAll(boolean editable) {
        textfID.setEditable(false);
        textfCost.setEditable(editable);
        textfName.setEditable(editable);
        textfProviderName.setEditable(editable);
        combType.setSelectedIndex(0);

    }

    public void clearAll() {
        textfCost.setText(null);
        textfID.setText(null);
        textfName.setText(null);
        textfProviderName.setText(null);
    }
    private void btnAddTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTypeActionPerformed

        UIControl.setLocationCenterForDialog(newIngredientTypeCreateDialog);
        newIngredientTypeCreateDialog.setVisible(true);
    }//GEN-LAST:event_btnAddTypeActionPerformed

    private void textfSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfSearchActionPerformed

    private void btnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportActionPerformed
        UIControl.setLocationCenterForDialog(ingredientImportDialog);
        ingredientImportDialog.setVisible(true);
    }//GEN-LAST:event_btnImportActionPerformed

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModifyActionPerformed

    private void textfProviderNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfProviderNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfProviderNameActionPerformed

    private void button_ShowImportHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ShowImportHistoryActionPerformed
        UIControl.setLocationCenterForDialog(history);
        history.setVisible(true);
    }//GEN-LAST:event_button_ShowImportHistoryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddType;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnImport;
    private javax.swing.JButton btnModify;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton button_ClearSearch;
    private javax.swing.JButton button_ShowImportHistory;
    private javax.swing.JComboBox<String> combType;
    private javax.swing.JLabel label_IngredientProvider;
    private javax.swing.JLabel label_Search;
    private javax.swing.JLabel label_ingreCost;
    private javax.swing.JLabel label_ingreID;
    private javax.swing.JLabel label_ingreName;
    private javax.swing.JLabel label_ingreType;
    private javax.swing.JPanel panelBtn;
    private javax.swing.JPanel panelIngredientInfo;
    private javax.swing.JScrollPane scrpaneIngredient;
    private javax.swing.JTable tableIngredient;
    private javax.swing.JTextField textfCost;
    private javax.swing.JTextField textfID;
    private javax.swing.JTextField textfName;
    private javax.swing.JTextField textfProviderName;
    private javax.swing.JTextField textfSearch;
    // End of variables declaration//GEN-END:variables
}
