/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.function.product;

import javax.swing.JTable;

/**
 *
 * @author Minh Tu
 */
public class ProductManagePanel extends javax.swing.JPanel {

    /**
     * Creates new form Function_ProductManagement
     */
    public ProductManagePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabbedPanel = new javax.swing.JTabbedPane();
        panelIngredient = new view.function.product.IngredientPanel();
        panelProvider = new view.function.product.ProviderPanel();
        panelProduct = new view.function.product.ProductPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        TabbedPanel.setBackground(new java.awt.Color(255, 255, 255));
        TabbedPanel.addTab("Ingredient", panelIngredient);
        TabbedPanel.addTab("Provider", panelProvider);
        TabbedPanel.addTab("Product", panelProduct);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1232, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 918, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabbedPanel;
    private view.function.product.IngredientPanel panelIngredient;
    private view.function.product.ProductPanel panelProduct;
    private view.function.product.ProviderPanel panelProvider;
    // End of variables declaration//GEN-END:variables
}
