/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.function.product;

import util.swing.UIControl;

/**
 *
 * @author DELL
 */
public class ProviderPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProviderManagePanel
     */
    public ProviderPanel() {
        initComponents();
        UIControl.setDefaultTableHeader(tableProduct);
        setEditableForAll(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelProviderInfo = new javax.swing.JPanel();
        label_provID4 = new javax.swing.JLabel();
        textfID = new javax.swing.JTextField();
        label_provName4 = new javax.swing.JLabel();
        label_provEmail4 = new javax.swing.JLabel();
        label_provMobile4 = new javax.swing.JLabel();
        textfPhoneNum = new javax.swing.JTextField();
        label_provAdd4 = new javax.swing.JLabel();
        textfName = new javax.swing.JTextField();
        textfEmail = new javax.swing.JTextField();
        textfAddress = new javax.swing.JTextField();
        textfSearch = new javax.swing.JTextField();
        label_searchProv = new javax.swing.JLabel();
        panelBtn = new javax.swing.JPanel();
        btnExport = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnModify = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        scrpaneTable = new javax.swing.JScrollPane();
        tableProduct = new javax.swing.JTable();
        cbbToSearch = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        button_ClearSearch = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        panelProviderInfo.setBackground(new java.awt.Color(255, 255, 255));
        panelProviderInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Provider Information", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 14), new java.awt.Color(153, 153, 153))); // NOI18N

        label_provID4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        label_provID4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        label_provID4.setText(" ID");

        textfID.setEditable(false);
        textfID.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        textfID.setEnabled(false);
        textfID.setPreferredSize(new java.awt.Dimension(160, 30));

        label_provName4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        label_provName4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        label_provName4.setText("Name");

        label_provEmail4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        label_provEmail4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        label_provEmail4.setText("Email");

        label_provMobile4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        label_provMobile4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        label_provMobile4.setText("Mobile");

        textfPhoneNum.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        textfPhoneNum.setPreferredSize(new java.awt.Dimension(160, 30));

        label_provAdd4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        label_provAdd4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        label_provAdd4.setText("Address");

        textfName.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        textfEmail.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        textfAddress.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        javax.swing.GroupLayout panelProviderInfoLayout = new javax.swing.GroupLayout(panelProviderInfo);
        panelProviderInfo.setLayout(panelProviderInfoLayout);
        panelProviderInfoLayout.setHorizontalGroup(
            panelProviderInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProviderInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProviderInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_provName4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_provID4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelProviderInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProviderInfoLayout.createSequentialGroup()
                        .addComponent(textfID, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(label_provMobile4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textfPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(textfName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProviderInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_provAdd4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_provEmail4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProviderInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textfEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                    .addComponent(textfAddress))
                .addContainerGap())
        );
        panelProviderInfoLayout.setVerticalGroup(
            panelProviderInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProviderInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProviderInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_provID4)
                    .addComponent(label_provMobile4)
                    .addComponent(textfPhoneNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_provEmail4)
                    .addComponent(textfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelProviderInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_provName4)
                    .addComponent(label_provAdd4)
                    .addComponent(textfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        textfSearch.setPreferredSize(new java.awt.Dimension(190, 30));

        label_searchProv.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        label_searchProv.setText("Type");

        panelBtn.setBackground(new java.awt.Color(255, 255, 255));
        panelBtn.setLayout(new java.awt.GridLayout(1, 0, 40, 0));

        btnExport.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        btnExport.setText("Export");
        btnExport.setFocusPainted(false);
        btnExport.setPreferredSize(new java.awt.Dimension(115, 40));
        panelBtn.add(btnExport);

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.setFocusPainted(false);
        btnAdd.setPreferredSize(new java.awt.Dimension(115, 40));
        panelBtn.add(btnAdd);

        btnModify.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        btnModify.setText("Modify");
        btnModify.setFocusPainted(false);
        btnModify.setPreferredSize(new java.awt.Dimension(115, 40));
        panelBtn.add(btnModify);

        btnRemove.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        btnRemove.setText("Remove");
        btnRemove.setFocusPainted(false);
        btnRemove.setPreferredSize(new java.awt.Dimension(115, 40));
        panelBtn.add(btnRemove);

        tableProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Provider ID", "Name", "Email", "Mobile", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrpaneTable.setViewportView(tableProduct);

        cbbToSearch.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        cbbToSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Name", "ID" }));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel1.setText("to search");

        button_ClearSearch.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        button_ClearSearch.setText("Clear");
        button_ClearSearch.setFocusPainted(false);
        button_ClearSearch.setPreferredSize(new java.awt.Dimension(89, 29));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrpaneTable)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(label_searchProv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbToSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_ClearSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addComponent(panelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(panelProviderInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(panelProviderInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label_searchProv)
                        .addComponent(cbbToSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(panelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_ClearSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrpaneTable, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    public void setEditableForAll(boolean editable) {
        textfID.setEditable(false);
        textfAddress.setEditable(editable);
        textfEmail.setEditable(editable);
        textfName.setEditable(editable);
        textfPhoneNum.setEditable(editable);

    }

    public void clearAll() {
        textfAddress.setText(null);
        textfEmail.setText(null);
        textfID.setText(null);
        textfName.setText(null);
        textfPhoneNum.setText(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnModify;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton button_ClearSearch;
    private javax.swing.JComboBox<String> cbbToSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel label_provAdd4;
    private javax.swing.JLabel label_provEmail4;
    private javax.swing.JLabel label_provID4;
    private javax.swing.JLabel label_provMobile4;
    private javax.swing.JLabel label_provName4;
    private javax.swing.JLabel label_searchProv;
    private javax.swing.JPanel panelBtn;
    private javax.swing.JPanel panelProviderInfo;
    private javax.swing.JScrollPane scrpaneTable;
    private javax.swing.JTable tableProduct;
    private javax.swing.JTextField textfAddress;
    private javax.swing.JTextField textfEmail;
    private javax.swing.JTextField textfID;
    private javax.swing.JTextField textfName;
    private javax.swing.JTextField textfPhoneNum;
    private javax.swing.JTextField textfSearch;
    // End of variables declaration//GEN-END:variables
}
